name: Update Changelog
on:
  push:
    tags: 
      - '*.*.*'

jobs:
  update-change-log:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install git-chglog
        uses: jaxxstorm/action-install-gh-release@v1.10.0 
        with: 
          platform: linux
          repo: git-chglog/git-chglog

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get tags
        run: |
          git fetch --tags origin
          git tag --list

      - name: Update Changelog
        run: git-chglog -o CHANGELOG.md
     
      - name: 'Get Previous tag'
        id: previous-stage
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
 
      - name: Commit changelog 
        uses: stefanzweifel/git-auto-commit-action@v4