name: Update Changelog
on:
  push:
    tags: 
      - '*.*.*'

jobs:
  update-change-log:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install git-chglog
        uses: jaxxstorm/action-install-gh-release@v1.10.0 
        with: 
          platform: linux
          repo: git-chglog/git-chglog

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tags # git-chglog uses tags, so they need to be fetched
        run: |
          git fetch --tags origin
          git tag --list

      - name: Update Changelog
        run: git-chglog -o CHANGELOG.md
     
      - name: 'Get Previous tag'
        id: previous-stage
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
 
      - name: Git commit / push
        working-directory: .
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'docs(changelog): update changelog to ${{ steps.previous-stage.outputs.tag }}'
          git push